jobs:
  - name: verify_infra_changes
    type: runSh
    steps:
      - IN: helpers
        switch: off
      - IN: state_infra
      - IN: creds_aws
        switch: off
      - IN: repo_infra
      - TASK:
        - script: IN/repo_infra/gitRepo/plan.sh state_infra
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
    flags:
      - infra

  - name: provision_infra
    type: runSh
    steps:
      - IN: helpers
        switch: off
      - IN: state_infra
      - IN: creds_aws
      - IN: repo_infra
        switch: off
      - IN: verify_infra_changes
        switch: off
      - TASK:
        - script: IN/repo_infra/gitRepo/provision.sh state_infra
      - OUT: state_infra
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
    always:
      - script: /build/IN/repo_infra/gitRepo/archiveState.sh state_infra
    flags:
      - infra

  - name: destroy_infra
    type: runSh
    steps:
      - IN: helpers
        switch: off
      - IN: state_infra
      - IN: creds_aws
      - IN: repo_infra
        switch: off
      - IN: verify_infra_changes
        switch: off
      - TASK:
        - script: IN/repo_infra/gitRepo/destroy.sh state_infra
      - OUT: state_infra
    on_success:
      - script: /build/IN/repo_infra/gitRepo/archiveState.sh state_infra
    on_failure:
      - script: echo 'failed'
    flags:
      - infra

  - name: bootstrap
    type: runSh
    steps:
      - IN: helpers
        switch: off
      - IN: creds_aws
        switch: off
      - IN: ssh_notes_deploy
        switch: off
      - IN: state_infra
        switch: off
      - IN: repo_infra
        switch: off
      - IN: provision_infra
        switch: off
      - TASK:
        - script: IN/repo_infra/gitRepo/bootstrap.sh
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
    flags:
      - infra

  - name: notes_runCI
    type: runCI
    steps:
      - OUT: image_notes
    flags:
      - dev

  - name: demoBlog_runCI
    type: runCI
    steps:
      - OUT: image_blog
    flags:
      - demo

  - name: deploy_notes
    type: runSh
    steps:
      - IN: helpers
        switch: off
      - IN: ssh_notes_deploy
      - IN: kv_notes_deploy
      - IN: image_notes
      - IN: bootstrap
        switch: off
      - TASK:
        - script: /build/IN/helpers/gitRepo/deploy_notes/do.sh
    flags:
      - dev

  - name: deploy_blog
    type: runSh
    steps:
      - IN: state_infra
      - IN: repo_infra
        switch: off
      - IN: creds_aws
      - IN: helpers
        switch: off
      - IN: ssh_notes_deploy
      - IN: image_blog
      - IN: bootstrap
        switch: off
      - TASK:
        - script: IN/helpers/gitRepo/deploy_blog/do.sh
    flags:
      - dev
