resources:
  - name: helpers
    type: gitRepo
    integration: scm_gl_ric03uec
    pointer:
      sourceName: ric03uec/helpers
      branch: master
    flags:
      - ric03uec_notes

  - name: reg_dh_ric03uec
    type: integration
    integration: reg_dh_ric03uec
    flags:
      - ric03uec_notes

  - name: notes_login_creds
    type: params
    version:
      params:
        secure: WQ215HoT8PvqGG0GKglFF1X9zGNJW5iP/yYMvb/aAul7uHs7NpysGsFipQe9JvKMajGptPhZjZHb9/w+b4/I6kSrgttSby3Io0EI0Zb0gc00XwZsxwGKT5SmtIZiZTLRMKCAqlKAUC7eHSNbAhTodXHBMEWPitV+E0bNPBJydJjfK0HVikBYud5g2kGiE0+4mW4gyItTzDQijb5yA1KGiOgUZRyHaJnHTNTbn6+RfDu/n1UGKXqSGYHWh+ShAZHf1vphnbjdXa4w0gNv35LyrmtCu6N3D8OJ9CeDIcDUsp17eV2zZEad7fT28B1uc+NenEvpmLoyM2TgwFZJn6i8lQ==
    flags:
      - ric03uec_notes

  - name: image_notes
    type: image
    integration: reg_dh_ric03uec
    pointer:
      sourceName: "ric03uec/notes"
    seed:
      versionName: ci
    flags:
      - ric03uec_notes

  - name: ssh_notes_deploy
    type: integration
    integration: ric03uec_gce_pem
    flags:
      - ric03uec_notes

  - name: repo_infra
    type: gitRepo
    integration: scm_gl_ric03uec
    pointer:
      sourceName: ric03uec/infra
      branch: master
    flags:
      - ric03uec_notes

  - name: state_gce
    type: state
    flags:
      - infra

  - name: slack
    type: notification
    integration: slack-ric03uec
    pointer:
      recipients:
        - "#builds"

jobs:
  - name: verify_infra_changes
    type: runSh
    steps:
      - IN: helpers
        switch: off
      - IN: state_gce
      - IN: repo_infra
      - TASK:
          name: "Verify infra changes"
          script:
          - echo "Verifying infra changes"
        # - IN/helpers/gitRepo/verify_infra_changes/do.sh
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
    flags:
      - infra

  - name: provision_infra
    type: runSh
    steps:
      - IN: helpers
        switch: off
      - IN: state_gce
      - IN: repo_infra
        switch: off
      - IN: verify_infra_changes
        switch: off
      - TASK:
          name: "Provision infra"
          script:
            - echo "Provisioning infrastructure on gce"
            #- IN/helpers/gitRepo/provision_infra/do.sh
      - OUT: state_gce
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
    flags:
      - infra

  - name: destroy_infra
    type: runSh
    steps:
      - IN: helpers
        switch: off
      - IN: state_gce
      - IN: repo_infra
        switch: off
      - IN: verify_infra_changes
        switch: off
      - TASK:
          name: "Destroy infra"
          script:
            - echo "Destroying infrastructure on gce"
          #- IN/helpers/gitRepo/destroy_infra/do.sh
      - OUT: state_gce
    on_failure:
      - script: echo 'failed'
    flags:
      - infra

  - name: bootstrap
    type: runSh
    steps:
      - IN: helpers
        switch: off
      - IN: state_gce
        switch: off
      - IN: repo_infra
        switch: off
      - IN: provision_infra
        switch: off
      - TASK:
          name: "Bootstraping machine with basic packages"
          script:
            - IN/helpers/gitRepo/bootstrap/do.sh
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
    flags:
      - ric03uec_notes

  - name: notes_runCI
    type: runCI
    steps:
      - OUT: image_notes
    flags:
      - ric03uec_notes

  - name: deploy_notes
    type: runSh
    steps:
      - IN: state_gce
        switch: off
      - IN: reg_dh_ric03uec
        switch: off
      - IN: notes_login_creds
        switch: off
      - IN: helpers
        switch: off
      - IN: repo_infra
        switch: off
      - IN: bootstrap
        switch: off
        #- IN: ssh_notes_deploy
      - IN: image_notes
      - TASK:
          script:
            - echo $BUILD_DIR
            - $BUILD_DIR/IN/helpers/gitRepo/deploy_notes/do.sh
    on_success:
      - NOTIFY: slack
    on_failure:
      - NOTIFY: slack
    flags:
      - ric03uec_notes
