jobs:
  - name: notes_runCI
    type: runCI
    flags:
      - dev
    steps:
      - OUT: image_notes

  - name: deploy_notes
    type: runSh
    flags:
      - dev
    steps:
      - IN: image_notes
      - IN: pipeline_master
        switch: off
      - TASK:
        - script: /build/IN/pipeline_master/gitRepo/scripts/deploy.sh

  - name: provision_infra
    type: runSh
    flags:
      - infra
    steps:
      - IN: state_infra
      - IN: creds_aws
      - IN: repo_infra
        switch: off
      - TASK:
        - script: IN/repo_infra/gitRepo/provision.sh
      - OUT: state_infra
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
    always:
      - script: /build/IN/repo_infra/gitRepo/archiveState.sh

  - name: destroy_infra
    type: runSh
    flags:
      - infra
    steps:
      - IN: state_infra
      - IN: creds_aws
      - IN: repo_infra
        switch: off
      - TASK:
        - script: echo "Running runsh task to destroy infra"
      - OUT: state_infra
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'

  - name: stop_instances
    type: runSh
    flags:
      - infra
    steps:
      - IN: creds_aws
      - IN: provision_infra
        switch: off
      - IN: repo_infra
        switch: off
      - TASK:
        - script: echo "Running runsh task to stop the instance"
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'

  - name: start_instances
    type: runSh
    flags:
      - infra
    steps:
      - IN: creds_aws
      - IN: provision_infra
        switch: off
      - IN: repo_infra
        switch: off
      - TASK:
        - script: echo "Running runsh task to start the instance"
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
