jobs:
  - name: infra-provision
    type: runSh
    flags:
      - infra
    steps:
      - IN: infra-state
      - IN: aws-creds
      - IN: infra-repo
        switch: off
      - TASK:
        - script: IN/infra-repo/gitRepo/provision.sh
      - OUT: infra-state
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
    always:
      - script: /build/IN/infra-repo/gitRepo/archiveState.sh

  - name: infra-destroy
    type: runSh
    flags:
      - infra
    steps:
      - IN: infra-state
      - IN: aws-creds
      - IN: infra-repo
        switch: off
      - TASK:
        - script: echo "Running runsh task to destroy infra"
      - OUT: infra-state
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'

  - name: instances-stop
    type: runSh
    flags:
      - infra
    steps:
      - IN: aws-creds
      - IN: infra-provision
        switch: off
      - IN: infra-repo
        switch: off
      - TASK:
        - script: echo "Running runsh task to stop the instance"
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'

  - name: instances-start
    type: runSh
    flags:
      - infra
    steps:
      - IN: aws-creds
      - IN: infra-provision
        switch: off
      - IN: infra-repo
        switch: off
      - TASK:
        - script: echo "Running runsh task to start the instance"
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
