jobs:
  - name: verify_infra_changes
    type: runSh
    steps:
      - IN: helpers
        switch: off
      - IN: state_infra
      - IN: creds_aws
        switch: off
      - IN: repo_infra
      - TASK:
        - script: IN/helpers/gitRepo/verify_infra_changes/do.sh
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
    flags:
      - infra

  - name: provision_infra
    type: runSh
    steps:
      - IN: helpers
        switch: off
      - IN: state_infra
      - IN: creds_aws
      - IN: repo_infra
        switch: off
      - IN: verify_infra_changes
        switch: off
      - TASK:
        - script: IN/helpers/gitRepo/provision_infra/do.sh
      - OUT: state_infra
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
    flags:
      - infra

  - name: destroy_infra
    type: runSh
    steps:
      - IN: helpers
        switch: off
      - IN: state_infra
      - IN: creds_aws
      - IN: repo_infra
        switch: off
      - IN: verify_infra_changes
        switch: off
      - TASK:
        - script: IN/helpers/gitRepo/destroy_infra/do.sh
      - OUT: state_infra
    on_failure:
      - script: echo 'failed'
    flags:
      - infra

  - name: bootstrap
    type: runSh
    steps:
      - IN: helpers
        switch: off
      - IN: creds_aws
        switch: off
      - IN: ssh_blog_deploy
        switch: off
      - IN: state_infra
        switch: off
      - IN: repo_infra
        switch: off
      - IN: provision_infra
        switch: off
      - TASK:
        - script: IN/helpers/gitRepo/bootstrap/do.sh
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
    flags:
      - infra

  - name: notes_runCI
    type: runCI
    steps:
      - OUT: image_notes
    flags:
      - dev

  - name: demoBlog_runCI
    type: runCI
    steps:
      - OUT: image_blog
    flags:
      - demo

  - name: deploy_notes
    type: runSh
    steps:
      - IN: state_infra
        switch: off
      - IN: reg_dh_ric03uec
        switch: off
      - IN: creds_aws
        switch: off
      - IN: notes_login_creds
        switch: off
      - IN: helpers
        switch: off
      - IN: repo_infra
        switch: off
      - IN: bootstrap
        switch: off
      - IN: ssh_notes_deploy
      - IN: image_notes
      - TASK:
        - script: /build/IN/helpers/gitRepo/deploy_notes/do.sh
    on_success:
      - NOTIFY: slack
    on_failure:
      - NOTIFY: slack
    flags:
      - dev

  - name: deploy_blog
    type: runSh
    steps:
      - IN: state_infra
        switch: off
      - IN: creds_aws
        switch: off
      - IN: helpers
        switch: off
      - IN: repo_infra
        switch: off
      - IN: bootstrap
        switch: off
      - IN: ssh_blog_deploy
      - IN: image_blog
      - TASK:
        - script: IN/helpers/gitRepo/deploy_blog/do.sh
    flags:
      - dev
