jobs:
  - name: notes_runCI
    type: runCI
    steps:
      - OUT: image_notes
    flags:
      - dev

  - name: deploy_notes
    type: runSh
    steps:
      - IN: helpers
        switch: off
      - IN: ssh_notes_deploy
      - IN: kv_notes_deploy
      - IN: image_notes
      - TASK:
        - script: /build/IN/helpers/gitRepo/deploy_notes/do.sh
    flags:
      - dev

  - name: provision_infra
    type: runSh
    steps:
      - IN: helpers
        switch: off
      - IN: state_infra
      - IN: creds_aws
      - IN: repo_infra
        switch: off
      - TASK:
        - script: IN/repo_infra/gitRepo/provision.sh
      - OUT: state_infra
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
    always:
      - script: /build/IN/repo_infra/gitRepo/archiveState.sh
    flags:
      - infra

  - name: destroy_infra
    type: runSh
    steps:
      - IN: helpers
        switch: off
      - IN: state_infra
      - IN: creds_aws
      - IN: repo_infra
        switch: off
      - TASK:
        - script: echo "Running runsh task to destroy infra"
      - OUT: state_infra
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
    flags:
      - infra

  - name: stop_instances
    type: runSh
    steps:
      - IN: helpers
        switch: off
      - IN: creds_aws
      - IN: provision_infra
        switch: off
      - IN: repo_infra
        switch: off
      - TASK:
        - script: echo "Running runsh task to stop the instance"
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
    flags:
      - infra

  - name: start_instances
    type: runSh
    steps:
      - IN: helpers
        switch: off
      - IN: creds_aws
      - IN: provision_infra
        switch: off
      - IN: repo_infra
        switch: off
      - TASK:
        - script: echo "Running runsh task to start the instance"
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
    flags:
      - infra
