jobs:
  - name: infra-provision
    type: runSh
    steps:
      - IN: aws-creds
      - IN: infra-repo
        switch: off
      - TASK:
        - script: echo "Running runsh task"
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
