jobs:
  - name: infra-provision
    type: runSh
    steps:
      - IN: aws-creds
      - IN: infra-repo
        switch: off
      - TASK:
        - script: IN/infra-repo/gitRepo/provision.sh
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'

  - name: infra-destroy
    type: runSh
    steps:
      - IN: aws-creds
      - IN: infra-repo
        switch: off
      - TASK:
        - script: echo "Running runsh task to destroy infra"
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'

  - name: instances-stop
    type: runSh
    steps:
      - IN: aws-creds
      - IN: infra-repo
        switch: off
      - TASK:
        - script: echo "Running runsh task to stop the instance"
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'

  - name: instances-start
    type: runSh
    steps:
      - IN: aws-creds
      - IN: infra-repo
        switch: off
      - TASK:
        - script: echo "Running runsh task to start the instance"
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
